#!/usr/local/bin/node

const dynasty = require('dynasty')({ accessKeyId: '.', secretAccessKey: '.' }, 'http://localhost:8000');

dynasty.create('Posts', { key_schema: { hash: ['slug', 'string'], range: ['posted', 'string'] } }).then((res) => {
  console.log('Created Posts table');
  console.log(res);
});

dynasty.create('sessions', { key_schema: { hash: ['id', 'string'] } }).then((res) => {
  console.log('Created sessions table');
  console.log(res);
});
